AWSTemplateFormatVersion: '2010-09-09'
Description: Web Stack for Frontend Services

Parameters:
  API_URL:
    Type: String
    Description: URL of the backend API

Resources:
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "web-frontend-${AWS::AccountId}-${AWS::Region}"
      AccessControl: PublicRead

  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub "${WebBucket.Arn}/*"

Outputs:
  WebBucketName:
    Description: Name of the frontend S3 bucket
    Value: !Ref WebBucket

  ApiUrlUsed:
    Description: The API URL passed to the web stack
    Value: !Ref API_URL
